### PR TITLE
Fix arrays of void* being converted incorrectly

### PR DESCRIPTION
**Pull request by Wertzui123**
I think this hardcoded system should be removed and the function should be recursive, so that e.g. any level of `void******` gets converted correclty.
Anyway, this workaround "fixes" the issue in some cases.

### CODE REVIEW

**Comment by medvednikov** [comment]
Thanks, I've just added ci.yml, please pull it and add a test to `/tests/`

**Comment by medvednikov** [comment]
I've just cleaned up the test folder.

The test names should be `6.types.c` and `6.types.out`.

**Comment by medvednikov** [comment]
The files you removed here were already removed in <https://github.com/vlang/c2v/commit/d7ac0c7b6830943c5441c94e17e62667a62e4934>

**Comment by medvednikov** [comment]
I don't know why the diff is 6k lines, you probably should re-submit the PR.

**Comment by Wertzui123** [comment]
I somehow messed up the git history, sorry. It's probably best to open a new PR.

> I don't know why the diff is 6k lines

Where does it show that?

**Pull request closed without merging**
