### PR TITLE
fix escaping runes (#116)

### LINKED ISSUE #116: Can't translate '\\'
test.c 
```c
int main() {
        char a = '\\';
        return 0;
}
```

c2v will generate a error:
```
/home/dfdd/v/test.v:6:1: error: unexpected eof, expecting `}`
    4 | fn main()  {
    5 |     a := `\`
    6 |     return
      | ^
    7 | }
    8 |

Internal vfmt error while formatting file: /home/dfdd/v/test.v.
Encountered a total of: 1 errors.
```

### PR DESCRIPTION
**Pull request by prantlf**
Attempts to fix #116.

### CODE REVIEW

**Comment by prantlf** [comment]
I couldn't find how to escape "`". I used "\x60".

**Comment by ArtemkaKun** [comment]
Hi. Can you add test also?

**Comment by prantlf** [comment]
Oh yes, of course, @ArtemkaKun. Is this the expected place?

**Comment by ArtemkaKun** [comment]
Yes. About ` escaping - can't you do that with common escaping \ ?

https://vosca.dev/p/20f52cba04

**Comment by prantlf** [comment]
Done. I must've made some mistake when I couldn't get it compiled at first.

**Pull request merged**
