### PR TITLE
remove print on optional else after if block

### PR DESCRIPTION
**Pull request by trollkarlen**
improve prints to give away location of non existent children

### CODE REVIEW

**Comment by trollkarlen** [comment]
Will rebase this as soon as https://github.com/vlang/c2v/pull/126 is in.

**Comment by ArtemkaKun** [comment]
See my comment above

**Comment by trollkarlen** [comment]
> See my comment above

except this comment, I see no comment but my own on this PR.

**Review by ArtemkaKun — CHANGES_REQUESTED** [review]

**Comment by ArtemkaKun** [comment]
Sorry, I forgot to press a button to start a review

**Pull request merged**
