### PR TITLE
fix var/const conflict, update format of test output, update json ignore

### PR DESCRIPTION
**Pull request by JalonSolov**
Had to fix `tests/5.struct.out` due to recent changes in `v fmt`.

Fixed https://github.com/vlang/v/issues/22116

### CODE REVIEW

**Comment by JalonSolov** [comment]
No idea why this is failing on macos... clang version, perhaps?

**Comment by spytheman** [comment]
I am checking on my m1 right now.

**Comment by spytheman** [comment]
It is reproducible locally.

**Comment by spytheman** [comment]
The getline functions is declared on the C side 🤔 : 
```
0[16:20:54]@m1: (master) /opt/v $ rg getline /Applications/Xcode.app/Contents/Developer//Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdio.h
358:ssize_t getline(char ** __restrict __linep, size_t * __restrict __linecapp, FILE * __restrict __stream) __OSX_AVAILABLE_STARTING(__MAC_10_7, __IPHONE_4_3);
```

**Comment by spytheman** [comment]
It is present in the JSON output too:
```
      "isUsed": true,
      "name": "getline",
      "mangledName": "_getline",
      "type": {
        "qualType": "ssize_t (char **restrict, size_t *restrict, FILE *restrict)"
      },
```

**Comment by spytheman** [comment]
Afaik it is a regression from eafdd3c . For now, I've changed the .out file for macos to match the new output, so that the CI can pass :-| .

**Pull request merged**
