### PR TITLE
Fix module name when generating wrapper

### PR DESCRIPTION
**Pull request by ArtemkaKun**
Before this PR, the module name was generated wrongly when generating a module for a single file, when the path to this file was relative

### CODE REVIEW

**Comment by spytheman** [comment]
Can you add a small test for that fix?

**Comment by ArtemkaKun** [comment]
Unfortunately, I have no time for now. I will do that asap

**Comment by JalonSolov** [comment]
The test would be to translate a C file with just enough in it to show that this fix works, and use relative paths when translating.

**Comment by ArtemkaKun** [comment]
> The test would be to translate a C file with just enough in it to show that this fix works, and use relative paths when translating.

The problem is that test runner script walks through every test file by abs path. I would need to somehow ignore one single file and convert its path to a relative. Not sure if adding this complication to test runner script will pay off

**Comment by JalonSolov** [comment]
Just generate the C file as part of your test.  Don't make it a permanent file that's checked in.

**Comment by ArtemkaKun** [comment]
I implemented a trick to run tests for both absolute and relative paths, so this should cover this case as well

**Pull request merged**
