### PR TITLE
Auto populate system headers

### PR DESCRIPTION
**Pull request by crackedmind**
Call `clang -xc++ -E -v` to get system headers instead of hardcoded array
It avoids some problems on windows.

### CODE REVIEW

**Comment by ArtemkaKun** [comment]
Hi, @crackedmind what is the status of this PR?

**Comment by crackedmind** [comment]
> Hi, @crackedmind what is the status of this PR?

In the work.

**Comment by felipensp** [comment]
> > Hi, @crackedmind what is the status of this PR?
> 
> In the work.

What is missing in the PR @crackedmind ? Thanks

**Comment by spytheman** [comment]
Obsoleted by https://github.com/vlang/c2v/pull/182

**Pull request closed without merging**
