### PR TITLE
Fix: record_decl() array out of range (fix #4)

### LINKED ISSUE #4: Get a weird V panic when translating stivale2
# i get this:
```
$ v translate .
C to V translator 0.3.1
"." is a directory, processing all C files in it recursively...

  translating ./stivale2.c    ... ================ V panic ================
   module: builtin
 function: get()
  message: array.get: index out of range (i == 134, a.len == 134)
     file: /home/vox/Documents/v/vlib/builtin/array.v:384
   v hash: 298dc77
=========================================
/tmp/v_1000/../../../../../../home/vox/Documents/v/vlib/builtin/builtin.c.v:53: at panic_debug: Backtrace
/tmp/v_1000/../../../../../../home/vox/Documents/v/vlib/builtin/array.v:384: by array_get
/tmp/v_1000/../../../../../../home/vox/.vmodules/c2v/c2v.v:875: by main__C2V_record_decl
/tmp/v_1000/../../../../../../home/vox/.vmodules/c2v/c2v.v:2316: by main__C2V_top_level
/tmp/v_1000/../../../../../../home/vox/.vmodules/c2v/c2v.v:2271: by main__C2V_translate_file
/tmp/v_1000/../../../../../../home/vox/.vmodules/c2v/c2v.v:2196: by main__main
/tmp/v_1000/../../../../../../tmp/v_1000/c2v.tmp.c:17589: by main
C2V failed to translate the C files. Please report it via GitHub.
```

Link to [stivale2](https://github.com/stivale/stivale/blob/master/stivale2.h)

### PR DESCRIPTION
**Pull request by ArtemkaKun**
record_decl() -> check if can take next node from inner tree

### CODE REVIEW

**Comment by medvednikov** [comment]
Is it possible to add a test for this?

**Comment by ArtemkaKun** [comment]
> Is it possible to add a test for this?

I can add a file for which wrapper can be generated after this fix. Also, when I messed in this code (print `c.tree.inner.len < c.node_i + 1` instead of `c.tree.inner.len > c.node_i + 1`), test number 4 failed, because expect `struct TUser {` but got `struct   {`

I'm not sure if this is enough. If not, I can write a test case strictly for that part of code :)

**Comment by ArtemkaKun** [comment]
Yes @medvednikov, this is covered by 4.struct test. I think it can be merged without additional tests

```
struct User {
    char *name;
    int age;
};

// lots of structs are typedef'ed in C
typedef struct {
    char *name;
    int age;
} TUser;
```

**Comment by medvednikov** [comment]
I see, thanks.

**Pull request merged**
