### PR TITLE
Fix arrays of void* being converted incorrectly

### PR DESCRIPTION
**Pull request by Wertzui123**
I think this hardcoded system should be removed and the function should be recursive, so that e.g. any level of void****** gets converted correclty.
Anyway, this workaround "fixes" the issue in some cases.

Note: I already opend another PR for this (#14), but somehow messed up the Git history there, so I closed it again.

### CODE REVIEW

**Comment by ArtemkaKun** [comment]
@Wertzui123 @medvednikov can you please finish with this PR asap, because I will potentially change the same block of code, so neither I nor @Wertzui123 will have merge conflicts when I will be ready with my PR

**Comment by Wertzui123** [comment]
The PR is already ready to merge, afaik.

**Comment by JalonSolov** [comment]
Need trailing EOLs on the test.c and test.out files.

**Comment by JalonSolov** [comment]
Weird.  CI is finding an error in an unrelated test.

**Comment by ArtemkaKun** [comment]
Unfortunately, tests run by CI are broken. PR #22 need to be merged first (when Alex or somebody else will fix a test number 5)

**Comment by ArtemkaKun** [comment]
@Wertzui123 Can you please merge last master to this branch?

**Comment by medvednikov** [comment]
Merged now that CI is working correctly. Sorry for the delay.

**Pull request merged**
