### PR TITLE
Remove `enum` directory

### PR DESCRIPTION
**Pull request by ArtemkaKun**
The directory contains only service stuff to generate values used in the node_kind.v. Since node_kind.v was changed, and the overall implementation of c2v is stable by now, files from the enum folder can be removed.

### CODE REVIEW

**Comment by medvednikov** [comment]
It will still be useful for new C++ nodes. I think the generator needs to be updated instead. The directory should be changed to `gen/` or something like that.

**Comment by ArtemkaKun** [comment]
Got it, will do

**Comment by ArtemkaKun** [comment]
@medvednikov Hi, what do you think now?

**Comment by ArtemkaKun** [comment]
@medvednikov

What was done in this PR:
- `types` file was sorted A -> Z
- `parse.v` file was removed
- `gen_str.v` file was refactored to generate NodeKind code and related dictionary with improvements (like auto snake_case for entries in `types` file)

**Pull request merged**
